# Generated by Django 3.0.8 on 2020-09-09 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_docente', models.CharField(max_length=120)),
                ('dni', models.IntegerField(unique=True)),
                ('secu_bla', models.TextField()),
                ('asignacion', models.TextField()),
                ('anexo', models.TextField()),
                ('fecha_de_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
