# Generated by Django 3.0.8 on 2020-09-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='asignacion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre_docente',
            field=models.CharField(max_length=80),
        ),
    ]
