# Generated by Django 3.0.8 on 2020-09-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_auto_20200910_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.IntegerField(max_length=12, unique=True),
        ),
    ]
