# Generated by Django 3.0.8 on 2020-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0003_auto_20200911_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
