# Generated by Django 3.0.8 on 2020-09-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0004_auto_20200911_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
