# Generated by Django 3.0.8 on 2020-09-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumnos', models.CharField(max_length=80)),
                ('dni_alumnos', models.IntegerField(max_length=12, unique=True)),
                ('cuil_alumnos', models.IntegerField(max_length=15, unique=True)),
                ('domicilio_alumnos', models.CharField(max_length=120)),
                ('email_alumno', models.EmailField(max_length=254)),
                ('num_contacto_alumno', models.IntegerField(max_length=15)),
                ('curso_alumno', models.CharField(default='nn', max_length=4)),
                ('num_legajo_alumno', models.CharField(max_length=30, unique=True)),
                ('nombre_tutor', models.CharField(max_length=80)),
                ('dni_tutor', models.IntegerField(max_length=12, unique=True)),
                ('num_contacto_tutor', models.IntegerField(max_length=15)),
                ('observacion_general', models.TextField(default='inserte la observacion del alumno aquí')),
                ('plan_ano_alumno', models.CharField(max_length=80)),
                ('especialidad_alumno', models.CharField(max_length=80)),
            ],
        ),
    ]
