# Generated by Django 3.0.8 on 2020-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cuil_alumnos',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni_alumnos',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni_tutor',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='num_contacto_alumno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='num_contacto_tutor',
            field=models.IntegerField(),
        ),
    ]
