# Generated by Django 3.0.8 on 2020-09-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20200911_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ano_alumno',
            field=models.CharField(choices=[('1', 'Año 1'), ('2', 'Año 2'), ('3', 'Año 3'), ('4', 'Año 4')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cuil_alumnos',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso_alumno',
            field=models.CharField(choices=[('A', 'Curso A'), ('B', 'Curso B'), ('C', 'Curso C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni_alumnos',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni_tutor',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='num_contacto_alumno',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='num_contacto_tutor',
            field=models.PositiveIntegerField(),
        ),
    ]
