# Generated by Django 3.0.8 on 2020-09-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cue', models.CharField(max_length=120)),
                ('domicilio', models.CharField(max_length=120)),
                ('telefono', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=120)),
                ('modalidad', models.CharField(max_length=120)),
                ('plan_estudio', models.TextField()),
            ],
        ),
    ]
